(function(){
  "use strict";
  const cfg=window.YEAR8_SCIENCE_FOLIO;
  const visualDeck=window.YEAR8_SCIENCE_FOLIO_VISUAL_DECK;
  const visualsBySection=Object.fromEntries((visualDeck?.cards||[]).map(card=>[card.sectionId,card]));
  const blank=()=>({schemaVersion:cfg.schemaVersion,buildId:cfg.buildId,sourceContractDigest:cfg.sourceContractDigest,identity:{name:"",className:""},records:{},attachments:{},updatedAt:null,migratedFrom:null});
  let state=load(),timer;
  const root=document.querySelector("#records"),saveStatus=document.querySelector("#save-status"),migrationStatus=document.querySelector("#migration-status");
  function load(){
    try{const current=JSON.parse(localStorage.getItem(cfg.storageKey));if(current?.buildId===cfg.buildId&&current.records)return current}catch(_){ }
    for(const key of cfg.legacyStorageKeys){try{const legacy=JSON.parse(localStorage.getItem(key));if(legacy){const migrated=blank();migrated.identity={name:legacy.identity?.name||legacy.studentName||"",className:legacy.identity?.className||""};for(const rec of cfg.records){const old=legacy.records?.[rec.sectionId]||legacy.sections?.[rec.sectionId];if(old&&typeof old==="object")migrated.records[rec.sectionId]={...old}}migrated.migratedFrom=key;migrated.updatedAt=new Date().toISOString();localStorage.setItem(cfg.storageKey,JSON.stringify(migrated));return migrated}}catch(_){ }}
    return blank();
  }
  const getRec=id=>(state.records[id]||={});
  function set(id,key,value){getRec(id)[key]=value;queue()}
  function queue(){saveStatus.textContent="SavingÃ¢â‚¬Â¦";clearTimeout(timer);timer=setTimeout(save,180)}
  function save(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(cfg.storageKey,JSON.stringify(state));saveStatus.textContent=`Saved on this device at ${new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}`}catch(_){saveStatus.textContent="Storage is full. Export or print the record now."}updateProgress()}
  function makeVisual(record){
    const visual=visualsBySection[record.sectionId];if(!visual)return null;
    const figure=document.createElement("figure");figure.className="folio-visual";figure.dataset.visualId=visual.id;
    const img=document.createElement("img");img.src=visual.path;img.alt=visual.altText;img.loading="lazy";img.decoding="async";
    const caption=document.createElement("figcaption");caption.textContent=visual.caption;
    const actions=document.createElement("div");actions.className="visual-actions";
    const link=document.createElement("a");link.className="open-larger";link.href=visual.path;link.target="_blank";link.rel="noopener noreferrer";link.textContent="Open larger";
    const details=document.createElement("details");details.className="visual-description";const summary=document.createElement("summary");summary.textContent="Read the visual description";const description=document.createElement("p");description.textContent=visual.longDescription;details.append(summary,description);actions.append(link,details);figure.append(img,caption,actions);return figure;
  }
  function makeRecord(record){
    const article=document.createElement("article");article.className="record";article.dataset.section=record.sectionId;
    const badge=document.createElement("span");badge.className="badge";const code=document.createElement("p");code.className="code";code.textContent=record.sectionId;const title=document.createElement("h3");title.textContent=record.title;article.append(badge,code,title);
    if(record.depthStudy){const note=document.createElement("p");note.className="depth-note";note.innerHTML="<strong>Five-hour depth-study record:</strong> preserve the question, evidence/data, processing, analysis, conclusion, reflection, sources and learning-time record. This page does not set assessment conditions or supply a practical method.";article.append(note)}
    const visual=makeVisual(record);if(visual)article.append(visual);
    record.fields.forEach(([key,labelText])=>{const label=document.createElement("label");label.textContent=labelText;const area=document.createElement("textarea");area.rows=4;area.value=getRec(record.sectionId)[key]||"";area.dataset.key=key;area.addEventListener("input",()=>{set(record.sectionId,key,area.value);refresh(article,record)});label.append(area);article.append(label)});
    const attach=document.createElement("div");attach.className="attachment-box";attach.innerHTML=`<label>Optional student-created evidence image<input type="file" accept="image/*"></label><p class="attachment-status">No image attached. Use only your own or teacher-authorised evidence.</p><div class="attachment-actions"><button type="button" class="secondary remove-image">Remove image</button></div>`;const preview=document.createElement("img");preview.className="attachment-preview";preview.alt=`Student-created evidence attached to ${record.sectionId}`;if(state.attachments?.[record.sectionId]){preview.src=state.attachments[record.sectionId];attach.insertBefore(preview,attach.querySelector(".attachment-actions"));attach.querySelector(".attachment-status").textContent="Evidence image saved inside this device-local record."}
    attach.querySelector("input").addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;try{state.attachments||={};state.attachments[record.sectionId]=await resizeImage(file);save();render();saveStatus.textContent="Evidence image resized and saved on this device."}catch(err){saveStatus.textContent=err.message}});
    attach.querySelector(".remove-image").addEventListener("click",()=>{if(state.attachments)delete state.attachments[record.sectionId];save();render()});article.append(attach);
    const actions=document.createElement("div");actions.className="record-actions";const theory=document.createElement("a");theory.className="theory-link pending";theory.textContent=`Theory link pending for ${record.sectionId}`;theory.setAttribute("aria-disabled","true");if(cfg.theoryAnchorStatus==="final"&&!record.theoryAnchor.startsWith("__")){theory.href=record.theoryAnchor;theory.textContent="Review the relevant theory";theory.classList.remove("pending");theory.removeAttribute("aria-disabled")}else theory.addEventListener("click",e=>e.preventDefault());actions.append(theory);article.append(actions);
    const dest=document.createElement("p");dest.className="destination";dest.innerHTML=`<strong>Evidence destination:</strong> ${record.title}`;article.append(dest);refresh(article,record);return article;
  }
  function refresh(article,record){const values=record.fields.map(([key])=>String(getRec(record.sectionId)[key]||"").trim());const started=values.some(Boolean)||Boolean(state.attachments?.[record.sectionId]);const complete=values.every(v=>v.length>=10);article.classList.toggle("started",started);article.classList.toggle("complete",complete);article.querySelector(".badge").textContent=complete?"Complete":started?"Started":"Not started"}
  function render(){root.replaceChildren();const picker=document.querySelector("#record-picker");picker.replaceChildren();let active=location.hash.replace("#record-","");if(!cfg.records.some(r=>r.sectionId===active))active=cfg.records[0].sectionId;[...new Set(cfg.records.map(r=>r.module))].forEach(module=>{const stage=document.createElement("section");stage.className="folio-stage";const heading=document.createElement("h3");heading.textContent=module;const list=document.createElement("div");list.className="record-list";cfg.records.filter(r=>r.module===module).forEach(r=>{const link=document.createElement("a");link.href=`#record-${r.sectionId}`;link.dataset.section=r.sectionId;link.className="record-choice";link.innerHTML=`<span>${r.sectionId}</span><strong>${r.title}</strong><small>${r.fields.length} evidence prompts</small>`;list.append(link)});stage.append(heading,list);picker.append(stage)});const record=cfg.records.find(r=>r.sectionId===active);const workspace=document.createElement("section");workspace.className="record-workspace";workspace.append(makeRecord(record));root.append(workspace);picker.querySelector(`[data-section="${active}"]`)?.classList.add("selected");picker.addEventListener("click",event=>{const link=event.target.closest(".record-choice");if(!link)return;event.preventDefault();location.hash=`record-${link.dataset.section}`;render();root.scrollIntoView({behavior:"smooth",block:"start"})},{once:true});updateProgress()}
  function updateProgress(){const started=cfg.records.filter(r=>r.fields.some(([key])=>String(getRec(r.sectionId)[key]||"").trim())||state.attachments?.[r.sectionId]).length;const complete=cfg.records.filter(r=>r.fields.every(([key])=>String(getRec(r.sectionId)[key]||"").trim().length>=10)).length;document.querySelector("#progress-text").textContent=`${started} of ${cfg.records.length} records started Ã‚Â· ${complete} complete`;document.querySelector("progress").value=started;const summary=document.querySelector("#folio-progress-summary");if(summary)summary.textContent=`${complete} ready Â· ${cfg.records.length-complete} to develop`}
  function resizeImage(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith("image/"))return reject(new Error("Choose an image file."));const reader=new FileReader();reader.onerror=()=>reject(new Error("The image could not be read."));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error("The image could not be opened."));img.onload=()=>{const scale=Math.min(1,1200/Math.max(img.width,img.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.78))};img.src=reader.result};reader.readAsDataURL(file)})}
  function download(name,content,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
  function exportHtml(){const sections=cfg.records.map(r=>`<section><h2>${escapeHtml(r.sectionId)} Ã¢â‚¬â€ ${escapeHtml(r.title)}</h2>${r.fields.map(([key,label])=>`<h3>${escapeHtml(label)}</h3><p>${escapeHtml(getRec(r.sectionId)[key]||"").replace(/\n/g,"<br>")}</p>`).join("")}${state.attachments?.[r.sectionId]?`<img src="${state.attachments[r.sectionId]}" alt="Student-created evidence for ${escapeHtml(r.sectionId)}">`:""}</section>`).join("");const html=`<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Year 8 Science folio Ã¢â‚¬â€ ${escapeHtml(state.identity.name)}</title><style>body{font:16px/1.5 system-ui;max-width:900px;margin:auto;padding:24px;color:#182b3e}section{break-inside:avoid;border-top:2px solid #667;padding-top:12px;margin-top:24px}h1,h2{line-height:1.2}h3{font-size:1rem;margin-bottom:0}p{white-space:normal;min-height:1.3em}img{max-width:100%;max-height:600px}@media print{body{max-width:none;padding:0}section{break-inside:avoid}}</style></head><body><h1>Year 8 Science folio</h1><p><strong>Student:</strong> ${escapeHtml(state.identity.name)}<br><strong>Class/group:</strong> ${escapeHtml(state.identity.className)}<br><strong>Exported:</strong> ${escapeHtml(new Date().toLocaleString())}</p><p>This self-contained file is a student evidence record. It is not proof of Google Classroom or Google Drive submission.</p>${sections}</body></html>`;download(`year-8-science-folio-${new Date().toISOString().slice(0,10)}.html`,html,"text/html")}
  async function imageDataUrl(assetPath){const response=await fetch(assetPath);if(!response.ok)throw new Error(`Could not include ${assetPath} in the export.`);const bytes=new Uint8Array(await response.arrayBuffer());let binary="";for(let offset=0;offset<bytes.length;offset+=0x8000)binary+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return `data:image/svg+xml;base64,${btoa(binary)}`}
  async function exportHtmlWithDeck(){
    saveStatus.textContent="Preparing self-contained exportÃ¢â‚¬Â¦";
    try{const embedded=Object.fromEntries(await Promise.all((visualDeck.cards||[]).map(async visual=>[visual.sectionId,await imageDataUrl(visual.path)])));const sections=cfg.records.map(r=>{const visual=visualsBySection[r.sectionId];return `<section><h2>${escapeHtml(r.sectionId)} Ã¢â‚¬â€ ${escapeHtml(r.title)}</h2>${visual?`<figure><img src="${embedded[r.sectionId]}" alt="${escapeHtml(visual.altText)}"><figcaption>${escapeHtml(visual.caption)}</figcaption><p>${escapeHtml(visual.longDescription)}</p></figure>`:""}${r.fields.map(([key,label])=>`<h3>${escapeHtml(label)}</h3><p>${escapeHtml(getRec(r.sectionId)[key]||"").replace(/\n/g,"<br>")}</p>`).join("")}${state.attachments?.[r.sectionId]?`<img src="${state.attachments[r.sectionId]}" alt="Student-created evidence for ${escapeHtml(r.sectionId)}">`:""}</section>`}).join("");const html=`<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Year 8 Science folio Ã¢â‚¬â€ ${escapeHtml(state.identity.name)}</title><style>body{font:16px/1.5 system-ui;max-width:900px;margin:auto;padding:24px;color:#182b3e}section{break-inside:avoid;border-top:2px solid #667;padding-top:12px;margin-top:24px}h1,h2{line-height:1.2}h3{font-size:1rem;margin-bottom:0}p{white-space:normal;min-height:1.3em}figure{margin:1rem 0}img{display:block;max-width:100%;max-height:600px;margin:auto}figcaption{margin-top:.5rem;color:#465867}@media print{body{max-width:none;padding:0}section,figure{break-inside:avoid}}</style></head><body><h1>Year 8 Science folio</h1><p><strong>Student:</strong> ${escapeHtml(state.identity.name)}<br><strong>Class/group:</strong> ${escapeHtml(state.identity.className)}<br><strong>Exported:</strong> ${escapeHtml(new Date().toLocaleString())}</p><p>This self-contained file is a student evidence record. It is not proof of Google Classroom or Google Drive submission.</p>${sections}</body></html>`;download(`year-8-science-folio-${new Date().toISOString().slice(0,10)}.html`,html,"text/html");saveStatus.textContent="Self-contained record exported with 12 accepted folio cards."}catch(err){saveStatus.textContent=err.message}}
  const name=document.querySelector("#student-name"),className=document.querySelector("#student-class");name.value=state.identity.name||"";className.value=state.identity.className||"";name.addEventListener("input",()=>{state.identity.name=name.value;queue()});className.addEventListener("input",()=>{state.identity.className=className.value;queue()});
  document.querySelector("#print").addEventListener("click",()=>{save();window.print()});document.querySelector("#backup").addEventListener("click",()=>{save();download(`year-8-science-folio-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),"application/json")});document.querySelector("#export-html").addEventListener("click",async()=>{save();await exportHtmlWithDeck()});
  document.querySelector("#restore").addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;try{const restored=JSON.parse(await file.text());if(restored.buildId!==cfg.buildId||!restored.records)throw new Error("This is not a current Year 8 Science folio backup.");state={...blank(),...restored};localStorage.setItem(cfg.storageKey,JSON.stringify(state));name.value=state.identity?.name||"";className.value=state.identity?.className||"";render();saveStatus.textContent="Backup restored and saved on this device."}catch(err){saveStatus.textContent=err.message}finally{e.target.value=""}});
  render();if(state.migratedFrom)migrationStatus.textContent=`Compatible identity and matching section records were copied from ${state.migratedFrom}; the old record was preserved.`;if(state.updatedAt)saveStatus.textContent=`Restored local folio saved ${new Date(state.updatedAt).toLocaleString()}`;
})();
