window.YEAR8_SCIENCE_FOLIO = {
  buildId: "year-8-science-2026-build-001",
  version: "1.1.0",
  schemaVersion: "1.0.0",
  storageKey: "year-8-science:folio:v1.0.0",
  legacyStorageKeys: ["year-8-science:folio:v0.1.0", "year-8-science:folio:v0.2.0"],
  sourceContractDigest: "sha256:642f12266c8416d6c34a5532709b594347cca6d2dda08ec19949601ae003974e",
  theoryAnchorStatus: "final",
  visualDeckStatus: "accepted",
  records: [
    {sectionId:"M01-S01",module:"Data science 1 - part A",title:"Data-source and provenance record",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m01/#theory-m01-s01-provenance-safe-use",visualRef:"VR-M01-S01",fields:[["source","Source or dataset title and location"],["producer","Who produced or collected it"],["context","How, when and why it was collected"],["safeUse","Privacy, consent or safe-use decision"],["limits","Bias, missing information or other limitation"]]},
    {sectionId:"M01-S02",module:"Data science 1 - part A",title:"Question, variables and dataset collection record",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m01/#theory-m01-s02-variables-data-types",visualRef:"VR-M01-S02",fields:[["question","Scientific question"],["independent","Independent variable or comparison"],["dependent","Dependent variable or measured response"],["consistent","Relevant variables or fields kept consistent"],["dataset","Dataset fields, units/categories, repetitions and provenance notes"]]},
    {sectionId:"M01-S03",module:"Data science 1 - part A",title:"Processed representation, conclusion and problem-solving justification",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m01/#theory-m01-s03-patterns-conclusions",visualRef:"VR-M01-S03",fields:[["representation","Representation title, axes/fields and processing choices"],["pattern","Pattern, trend or relationship"],["conclusion","Evidence-based conclusion"],["limitation","Uncertainty or limitation"],["justification","How the evidence supports a problem-solving decision"]]},
    {sectionId:"M02-S01",module:"Living systems",title:"Annotated system representation and interrelationship explanation",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m02/#theory-m02-s01-system-interrelationships",visualRef:"VR-M02-S01",fields:[["representation","Describe or attach the annotated system representation"],["components","Key components and functions"],["relationship","Material or information exchanged between systems"],["consequence","Consequence if one component cannot perform its function"]]},
    {sectionId:"M02-S02",module:"Living systems",title:"Plant structure-function comparison and communicated explanation",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m02/#theory-m02-s02-specialised-tissues",visualRef:"VR-M02-S02",fields:[["comparison","Plant structure-function comparison"],["transport","How materials move through the plant"],["explanation","How the structures work together in a multicellular organism"],["communication","Caption or explanation prepared for another student"]]},
    {sectionId:"M02-S03",module:"Living systems",title:"Food-web or energy-pyramid representation and population-data conclusion",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m02/#theory-m02-s03-populations-extinction",visualRef:"VR-M02-S03",fields:[["representation","Describe or attach the food-web or energy-pyramid representation"],["population","Population-data pattern"],["conclusion","Evidence-based ecosystem conclusion"],["limitation","Why the pattern alone does not prove cause"]]},
    {sectionId:"M03-S01",module:"Periodic table and atomic structure",title:"Property/classification table and evidence-based use recommendation",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m03/#theory-m03-s01-selecting-materials",visualRef:"VR-M03-S01",fields:[["table","Matter/property classification table or summary"],["property","Relevant property evidence"],["recommendation","Recommended use or material"],["justification","Why the property evidence supports the recommendation"]]},
    {sectionId:"M03-S02",module:"Periodic table and atomic structure",title:"Annotated atomic model and model-change explanation",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m03/#theory-m03-s02-changing-scientific-models",visualRef:"VR-M03-S02",fields:[["model","Describe or attach the annotated atomic model"],["components","Particles/components represented"],["evidence","Evidence that prompted a model change"],["explanation","Why the revised model was more useful and still had limitations"]]},
    {sectionId:"M03-S03",module:"Periodic table and atomic structure",title:"Periodic-pattern analysis and element/compound interpretation",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m03/#theory-m03-s03-periods-groups-patterns",visualRef:"VR-M03-S03",fields:[["pattern","Pattern among the first 18 elements"],["evidence","Atomic numbers, groups, periods or symbols used as evidence"],["formula","Element or compound-symbol interpretation"],["limit","A claim the pattern does not justify by itself"]]},
    {sectionId:"M04-S01",module:"Change",title:"Energy-system representation and transfer/transformation explanation",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m04/#theory-m04-s01-energy-spread-and-diagrams",visualRef:"VR-M04-S01",fields:[["system","Describe or attach the energy-system representation"],["input","Energy input/store"],["transfers","Transfers or transformations"],["outputs","Useful output and transfer to surroundings"],["explanation","Whole-system explanation"]]},
    {sectionId:"M04-S02",module:"Change",title:"Observation record, word-equation explanation and investigation reflection",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m04/#theory-m04-s02-conservation-and-evidence-quality",visualRef:"VR-M04-S02",fields:[["observations","Teacher-supplied or source-recorded observations"],["classification","Physical or chemical classification with evidence"],["equation","Relevant word equation, if supported by the taught example"],["reflection","What the evidence supports and what remains uncertain"]]},
    {sectionId:"M04-S03",module:"Change",title:"Geological model and claim-evidence-reasoning response",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m04/#theory-m04-s03-plate-evidence-models",visualRef:"VR-M04-S03",fields:[["model","Describe or attach the geological model"],["claim","Claim about geological change"],["evidence","Rock, fossil, magnetic, earthquake, volcano or plate evidence used"],["reasoning","Reasoning that connects the evidence to the claim"],["limitation","Limitation or alternative explanation to consider"]]},
    {sectionId:"M05-S01",module:"Data science 1 - part B and depth study",title:"Model components, evidence and limitation analysis",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m05/#theory-m05-s01-limitations-appropriate-use",visualRef:null,fields:[["purpose","Model purpose and system represented"],["components","Inputs, components, relationships and outputs"],["evidence","Observation or dataset used to evaluate the model"],["strength","Useful feature or successful prediction"],["limitation","Assumption, omitted factor or other limitation"]]},
    {sectionId:"M05-S02",module:"Data science 1 - part B and depth study",title:"Prediction, parameter-change and model-evaluation response",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m05/#theory-m05-s02-evaluating-applications",visualRef:null,fields:[["parameter","Parameter changed"],["prediction","Prediction before the simulation"],["result","Simulation output or pattern"],["comparison","Comparison of prediction and output"],["evaluation","Usefulness, uncertainty and limitation of the model"]]},
    {sectionId:"M05-S03",module:"Data science 1 - part B and depth study",title:"Five-hour depth-study portfolio",theoryAnchor:"/Year-8-Science-Guided-Course/modules/y8s-m05/#theory-m05-s03-analysis-and-conclusion",visualRef:null,depthStudy:true,fields:[["question","Teacher-approved scientific question"],["sourceRecord","Evidence/data source and provenance record"],["evidenceData","Collected or supplied evidence/data record"],["representation","Processed table, graph, model or other representation"],["analysis","Patterns, relationships, uncertainty and limitations"],["conclusion","Conclusion that answers the question using evidence"],["reflection","Reflection on decisions, evidence quality and developing understanding"],["references","Source list and acknowledgements"],["timeRecord","Learning-time record contributing to the five-hour depth study"]]}
  ]
};

(() => {
  const config = window.YEAR8_SCIENCE_FOLIO;
  const bindings = {
    "M01-S01": { claims:["theory-m01-s01-data-sources","theory-m01-s01-digital-traces","theory-m01-s01-provenance-safe-use"], help:"theory-m01-s01-provenance-safe-use" },
    "M01-S02": { claims:["theory-m01-s02-scientific-questions","theory-m01-s02-variables-data-types","theory-m01-s02-collecting-quality-data"], help:"theory-m01-s02-variables-data-types" },
    "M01-S03": { claims:["theory-m01-s03-representing-data","theory-m01-s03-patterns-conclusions","theory-m01-s03-evaluating-solutions"], help:"theory-m01-s03-patterns-conclusions" },
    "M02-S01": { claims:["theory-m02-s01-levels-of-organisation","theory-m02-s01-major-body-systems","theory-m02-s01-system-interrelationships"], help:"theory-m02-s01-system-interrelationships" },
    "M02-S02": { claims:["theory-m02-s02-plant-organs","theory-m02-s02-specialised-tissues","theory-m02-s02-connected-plant-system"], help:"theory-m02-s02-specialised-tissues" },
    "M02-S03": { claims:["theory-m02-s03-ecosystem-relationships","theory-m02-s03-energy-food-webs","theory-m02-s03-populations-extinction"], help:"theory-m02-s03-populations-extinction" },
    "M03-S01": { claims:["theory-m03-s01-classifying-matter","theory-m03-s01-properties-groups","theory-m03-s01-selecting-materials"], help:"theory-m03-s01-selecting-materials" },
    "M03-S02": { claims:["theory-m03-s02-atomic-structure","theory-m03-s02-reading-simple-models","theory-m03-s02-changing-scientific-models"], help:"theory-m03-s02-changing-scientific-models" },
    "M03-S03": { claims:["theory-m03-s03-symbols-and-atomic-number","theory-m03-s03-periods-groups-patterns","theory-m03-s03-symbols-and-formulas"], help:"theory-m03-s03-periods-groups-patterns" },
    "M04-S01": { claims:["theory-m04-s01-systems-and-stores","theory-m04-s01-transfers-and-transformations","theory-m04-s01-energy-spread-and-diagrams"], help:"theory-m04-s01-energy-spread-and-diagrams" },
    "M04-S02": { claims:["theory-m04-s02-physical-and-chemical-change","theory-m04-s02-evidence-and-word-equations","theory-m04-s02-conservation-and-evidence-quality"], help:"theory-m04-s02-conservation-and-evidence-quality" },
    "M04-S03": { claims:["theory-m04-s03-geological-change-rock-cycle","theory-m04-s03-fossils-layers-relative-age","theory-m04-s03-plate-evidence-models"], help:"theory-m04-s03-plate-evidence-models" },
    "M05-S01": { claims:["theory-m05-s01-model-purpose-components","theory-m05-s01-models-and-evidence","theory-m05-s01-limitations-appropriate-use"], help:"theory-m05-s01-limitations-appropriate-use" },
    "M05-S02": { claims:["theory-m05-s02-simulation-components","theory-m05-s02-predictions-and-evidence","theory-m05-s02-evaluating-applications"], help:"theory-m05-s02-evaluating-applications" },
    "M05-S03": { claims:["theory-m05-s03-question-and-evidence","theory-m05-s03-analysis-and-conclusion","theory-m05-s03-reflection-and-source-record"], help:"theory-m05-s03-analysis-and-conclusion" }
  };
  config.theoryAnchorStatus = "final";
  config.theoryRouteConvention = "../theory.html#<anchor>";
  config.theoryManifestDigest = "sha256:17e4c0ff60294e4c1661104ce0d6cfad9c00419adb782e4911deeb706900838b";
  config.theoryClaimAnchorsBySection = Object.fromEntries(Object.entries(bindings).map(([id, binding]) => [id, binding.claims]));
  config.records.forEach((record) => {
    record.theoryClaimAnchors = bindings[record.sectionId].claims;
    record.theoryAnchor = `../theory.html#${bindings[record.sectionId].help}`;
  });
})();
