window.YEAR8_SCIENCE_VIDEO_LIBRARY = {
  buildId: "year-8-science-2026-build-001",
  version: "1.0.0",
  storageKey: "year-8-science:youtube-learning:v1.0.0",
  sourceContractDigest: "sha256:642f12266c8416d6c34a5532709b594347cca6d2dda08ec19949601ae003974e",
  validatedAt: "2026-08-09T08:56:17.8194146+10:00",
  validationMethod: "YouTube oEmbed metadata PASS and youtube-nocookie embed endpoint HTTP 200; content/topic suitability reviewed against the fixed v0.3.0 section boundary.",
  theoryAnchorStatus: "final",
  clips: [
    { sectionId:"M01-S01", module:"Data science 1 - part A", videoId:"ottnH427Fr8", title:"Teen Voices: Oversharing and Your Digital Footprint", channel:"Common Sense Education", focus:"Identify two kinds of information a digital trace can reveal and one safe-engagement choice.", prompt:"Record a source/provenance note for the clip, then explain how a scientific use of digital traces could protect personal information.", evidenceDestination:"Data-source and provenance record", theoryAnchor:"../theory.html#theory-m01-s01-provenance-safe-use" },
    { sectionId:"M01-S02", module:"Data science 1 - part A", videoId:"yC9Ym8xZboo", title:"Independent Variable vs. Dependent Variable #biology", channel:"Biology Kids", focus:"Listen for the distinction between the factor changed and the response measured.", prompt:"Write a scientific question for a hypothetical dataset and name its independent and dependent variables.", evidenceDestination:"Question, variables and dataset collection record", theoryAnchor:"../theory.html#theory-m01-s02-variables-data-types" },
    { sectionId:"M01-S03", module:"Data science 1 - part A", videoId:"LTqy-CH50zs", title:"Data Science for Beginners: Your 3-Minute Crash Course", channel:"Coursera", focus:"Notice how questions, data, processing and communication form a problem-solving cycle.", prompt:"Describe one pattern a processed dataset might reveal and one limit that should accompany the conclusion.", evidenceDestination:"Processed representation, conclusion and problem-solving justification", theoryAnchor:"../theory.html#theory-m01-s03-patterns-conclusions" },
    { sectionId:"M02-S01", module:"Living systems", videoId:"0JDCViWGn-0", title:"Human Body Systems Overview (Updated 2024)", channel:"Amoeba Sisters", focus:"Track how two body systems exchange materials or information rather than listing systems in isolation.", prompt:"Explain one interrelationship between two body systems and predict a consequence if that exchange is disrupted.", evidenceDestination:"Annotated system representation and interrelationship explanation", theoryAnchor:"../theory.html#theory-m02-s01-system-interrelationships" },
    { sectionId:"M02-S02", module:"Living systems", videoId:"jtuX7H05tmQ", title:"Xylem and Phloem - Transport in Plants | Biology | FuseSchool", channel:"FuseSchool - Global Education", focus:"Compare the material moved, direction and structure-function relationship of xylem and phloem.", prompt:"Write a two-column comparison of xylem and phloem, then explain how both support a multicellular plant.", evidenceDestination:"Plant structure-function comparison and communicated explanation", theoryAnchor:"../theory.html#theory-m02-s02-specialised-tissues" },
    { sectionId:"M02-S03", module:"Living systems", videoId:"2lqhJNgn_Wg", title:"Food Chains & Food Webs | Ecology & Environment | Biology | FuseSchool", channel:"FuseSchool - Global Education", focus:"Distinguish a single energy pathway from the interconnected relationships in a food web.", prompt:"Sketch or describe one food-web connection and explain how a population change could affect another population without claiming one observation proves cause.", evidenceDestination:"Food-web or energy-pyramid representation and population-data conclusion", theoryAnchor:"../theory.html#theory-m02-s03-populations-extinction" },
    { sectionId:"M03-S01", module:"Periodic table and atomic structure", videoId:"dggHWvFJ8Xs", title:"Types of Matter: Elements, Compounds, and Mixtures", channel:"Professor Dave Explains", focus:"Use composition and properties to distinguish elements, compounds and mixtures.", prompt:"Classify one example from the clip and justify a possible use by connecting it to a stated property.", evidenceDestination:"Property/classification table and evidence-based use recommendation", theoryAnchor:"../theory.html#theory-m03-s01-selecting-materials" },
    { sectionId:"M03-S02", module:"Periodic table and atomic structure", videoId:"9B3DDY27ZtE", title:"History of Atomic Theory", channel:"Professor Dave Explains", focus:"Listen for evidence that caused an atomic model to be revised, not just the names and dates.", prompt:"Choose one change in the atomic model and explain what new evidence made the revised model more useful.", evidenceDestination:"Annotated atomic model and model-change explanation", theoryAnchor:"../theory.html#theory-m03-s02-changing-scientific-models" },
    { sectionId:"M03-S03", module:"Periodic table and atomic structure", videoId:"P6DMEgE8CK8", title:"How Does The Periodic Table Work | Properties of Matter | Chemistry | FuseSchool", channel:"FuseSchool - Global Education", focus:"Connect atomic number, symbols, periods and groups to patterns rather than memorising positions alone.", prompt:"Describe one pattern visible among the first 18 elements and interpret the symbols in one simple compound formula.", evidenceDestination:"Periodic-pattern analysis and element/compound interpretation", theoryAnchor:"../theory.html#theory-m03-s03-periods-groups-patterns" },
    { sectionId:"M04-S01", module:"Change", videoId:"JGwcDCeYRYo", title:"GCSE Physics - Energy Stores, Transferring Energy & Work Done", channel:"Cognito", focus:"Separate an energy store from the pathway by which energy is transferred between system components.", prompt:"Represent one energy system from the clip with an input, a transfer, a useful output and energy transferred to the surroundings.", evidenceDestination:"Energy-system representation and transfer/transformation explanation", theoryAnchor:"../theory.html#theory-m04-s01-energy-spread-and-diagrams" },
    { sectionId:"M04-S02", module:"Change", videoId:"x49BtB5dOwg", title:"Physical and Chemical Changes: Chemistry for Kids - FreeSchool", channel:"Free School", focus:"Use observations and the formation of new substances to distinguish physical and chemical change.", prompt:"Select one example and give an evidence-based classification. State why a single observation may be insufficient for an unfamiliar change.", evidenceDestination:"Observation record, word-equation explanation and investigation reflection", theoryAnchor:"../theory.html#theory-m04-s02-conservation-and-evidence-quality" },
    { sectionId:"M04-S03", module:"Change", videoId:"SbIpWHQI-tE", title:"The continents are moving. When will they collide? - Jean-Baptiste P. Koehl", channel:"TED-Ed", focus:"Identify evidence and model-based reasoning used to explain plate motion and long-term geological change.", prompt:"Write a claim-evidence-reasoning paragraph connecting one observation to moving plates, then state a limitation of that evidence.", evidenceDestination:"Geological model and claim-evidence-reasoning response", theoryAnchor:"../theory.html#theory-m04-s03-plate-evidence-models" },
    { sectionId:"M05-S01", module:"Data science 1 - part B and depth study", videoId:"ysGuXBbbtaA", title:"Strengths and Limitations of Scientific Models | Grade 8 Science Week 33 Day 3", channel:"HeroesMart Homeschool Academy", focus:"Judge a model by its purpose, evidence, useful features and limitations rather than asking whether it is simply right or wrong.", prompt:"Name one component, one evidence check and one limitation of a scientific model discussed or implied in the clip.", evidenceDestination:"Model components, evidence and limitation analysis", theoryAnchor:"../theory.html#theory-m05-s01-limitations-appropriate-use" },
    { sectionId:"M05-S02", module:"Data science 1 - part B and depth study", videoId:"vn5k8acYcS8", title:"Computer Simulation: Exploring nature with a computer", channel:"Lawrence Livermore National Laboratory", focus:"Notice how simulations use parameters and computing to explore systems that may be difficult to observe directly.", prompt:"Predict how changing one parameter could change an output, then explain why a simulation result is not certainty.", evidenceDestination:"Prediction, parameter-change and model-evaluation response", theoryAnchor:"../theory.html#theory-m05-s02-evaluating-applications" },
    { sectionId:"M05-S03", module:"Data science 1 - part B and depth study", videoId:"Ti3nUDNK8iA", title:"Science Notebooking - How I Use My Science Notebook  | California Academy of Sciences", channel:"California Academy of Sciences", focus:"Observe how a science notebook preserves questions, observations, evidence and developing explanations.", prompt:"List the six portfolio parts you will preserve: question, evidence/data, analysis, conclusion, reflection and source record. Explain how the record shows changes in your thinking.", evidenceDestination:"Printable question, evidence/data, analysis, conclusion, reflection and source record", theoryAnchor:"../theory.html#theory-m05-s03-analysis-and-conclusion" }
  ]
};

(() => {
  const config = window.YEAR8_SCIENCE_VIDEO_LIBRARY;
  const bindings = {
    "M01-S01": { claims:["theory-m01-s01-data-sources","theory-m01-s01-digital-traces","theory-m01-s01-provenance-safe-use"], help:"theory-m01-s01-provenance-safe-use" },
    "M01-S02": { claims:["theory-m01-s02-scientific-questions","theory-m01-s02-variables-data-types","theory-m01-s02-collecting-quality-data"], help:"theory-m01-s02-variables-data-types" },
    "M01-S03": { claims:["theory-m01-s03-representing-data","theory-m01-s03-patterns-conclusions","theory-m01-s03-evaluating-solutions"], help:"theory-m01-s03-patterns-conclusions" },
    "M02-S01": { claims:["theory-m02-s01-levels-of-organisation","theory-m02-s01-major-body-systems","theory-m02-s01-system-interrelationships"], help:"theory-m02-s01-system-interrelationships" },
    "M02-S02": { claims:["theory-m02-s02-plant-organs","theory-m02-s02-specialised-tissues","theory-m02-s02-connected-plant-system"], help:"theory-m02-s02-specialised-tissues" },
    "M02-S03": { claims:["theory-m02-s03-ecosystem-relationships","theory-m02-s03-energy-food-webs","theory-m02-s03-populations-extinction"], help:"theory-m02-s03-populations-extinction" },
    "M03-S01": { claims:["theory-m03-s01-classifying-matter","theory-m03-s01-properties-groups","theory-m03-s01-selecting-materials"], help:"theory-m03-s01-selecting-materials" },
    "M03-S02": { claims:["theory-m03-s02-atomic-structure","theory-m03-s02-reading-simple-models","theory-m03-s02-changing-scientific-models"], help:"theory-m03-s02-changing-scientific-models" },
    "M03-S03": { claims:["theory-m03-s03-symbols-and-atomic-number","theory-m03-s03-periods-groups-patterns","theory-m03-s03-symbols-and-formulas"], help:"theory-m03-s03-periods-groups-patterns" },
    "M04-S01": { claims:["theory-m04-s01-systems-and-stores","theory-m04-s01-transfers-and-transformations","theory-m04-s01-energy-spread-and-diagrams"], help:"theory-m04-s01-energy-spread-and-diagrams" },
    "M04-S02": { claims:["theory-m04-s02-physical-and-chemical-change","theory-m04-s02-evidence-and-word-equations","theory-m04-s02-conservation-and-evidence-quality"], help:"theory-m04-s02-conservation-and-evidence-quality" },
    "M04-S03": { claims:["theory-m04-s03-geological-change-rock-cycle","theory-m04-s03-fossils-layers-relative-age","theory-m04-s03-plate-evidence-models"], help:"theory-m04-s03-plate-evidence-models" },
    "M05-S01": { claims:["theory-m05-s01-model-purpose-components","theory-m05-s01-models-and-evidence","theory-m05-s01-limitations-appropriate-use"], help:"theory-m05-s01-limitations-appropriate-use" },
    "M05-S02": { claims:["theory-m05-s02-simulation-components","theory-m05-s02-predictions-and-evidence","theory-m05-s02-evaluating-applications"], help:"theory-m05-s02-evaluating-applications" },
    "M05-S03": { claims:["theory-m05-s03-question-and-evidence","theory-m05-s03-analysis-and-conclusion","theory-m05-s03-reflection-and-source-record"], help:"theory-m05-s03-analysis-and-conclusion" }
  };
  config.theoryAnchorStatus = "final";
  config.theoryRouteConvention = "../theory.html#<anchor>";
  config.theoryManifestDigest = "sha256:17e4c0ff60294e4c1661104ce0d6cfad9c00419adb782e4911deeb706900838b";
  config.theoryClaimAnchorsBySection = Object.fromEntries(Object.entries(bindings).map(([id, binding]) => [id, binding.claims]));
  config.clips.forEach((clip) => {
    clip.theoryClaimAnchors = bindings[clip.sectionId].claims;
    clip.theoryAnchor = `../theory.html#${bindings[clip.sectionId].help}`;
  });
})();
